version: '3.8'

services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: jobapptailor
      POSTGRES_USER: jobapp_user
      POSTGRES_PASSWORD: jobapp_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/jobapptailor
      SPRING_DATASOURCE_USERNAME: jobapp_user
      SPRING_DATASOURCE_PASSWORD: jobapp_password
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      JWT_SECRET: ${JWT_SECRET:-your-jwt-secret-key-here}
    depends_on:
      - database
    networks:
      - app-network
    volumes:
      - ./backend:/app
      - /app/target

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
